/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeTreatRouteImport } from './routes/what-we-treat'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MichiganDiscoveryCallRouteImport } from './routes/michigan-discovery-call'
import { Route as FreeGuideRouteImport } from './routes/free-guide'
import { Route as Free15MinCallWithKatieRouteImport } from './routes/free-15-min-call-with-katie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClaritySessionRouteImport } from './routes/clarity-session'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRouteImport } from './routes/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
import { Route as BlogTheUltimateGuideToHormonesAndWeightResistanceOver40RouteImport } from './routes/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40'
import { Route as BlogPerimenopauseInYour30sMichiganWisconsinRouteImport } from './routes/blog/perimenopause-in-your-30s-michigan-wisconsin'
import { Route as BlogOzempicNotWorkingMichiganWisconsinWomenRouteImport } from './routes/blog/ozempic-not-working-michigan-wisconsin-women'
import { Route as BlogHormonalSleepAnxietyWomenMichiganWisconsinRouteImport } from './routes/blog/hormonal-sleep-anxiety-women-michigan-wisconsin'
import { Route as BlogGainingWeightExhaustedAfter40WisconsinWomenRouteImport } from './routes/blog/gaining-weight-exhausted-after-40-wisconsin-women'
import { Route as BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRouteImport } from './routes/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin'

const WhatWeTreatRoute = WhatWeTreatRouteImport.update({
  id: '/what-we-treat',
  path: '/what-we-treat',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MichiganDiscoveryCallRoute = MichiganDiscoveryCallRouteImport.update({
  id: '/michigan-discovery-call',
  path: '/michigan-discovery-call',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeGuideRoute = FreeGuideRouteImport.update({
  id: '/free-guide',
  path: '/free-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const Free15MinCallWithKatieRoute = Free15MinCallWithKatieRouteImport.update({
  id: '/free-15-min-call-with-katie',
  path: '/free-15-min-call-with-katie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaritySessionRoute = ClaritySessionRouteImport.update({
  id: '/clarity-session',
  path: '/clarity-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute =
  BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRouteImport.update({
    id: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted',
    path: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route =
  BlogTheUltimateGuideToHormonesAndWeightResistanceOver40RouteImport.update({
    id: '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40',
    path: '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPerimenopauseInYour30sMichiganWisconsinRoute =
  BlogPerimenopauseInYour30sMichiganWisconsinRouteImport.update({
    id: '/blog/perimenopause-in-your-30s-michigan-wisconsin',
    path: '/blog/perimenopause-in-your-30s-michigan-wisconsin',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogOzempicNotWorkingMichiganWisconsinWomenRoute =
  BlogOzempicNotWorkingMichiganWisconsinWomenRouteImport.update({
    id: '/blog/ozempic-not-working-michigan-wisconsin-women',
    path: '/blog/ozempic-not-working-michigan-wisconsin-women',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute =
  BlogHormonalSleepAnxietyWomenMichiganWisconsinRouteImport.update({
    id: '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin',
    path: '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGainingWeightExhaustedAfter40WisconsinWomenRoute =
  BlogGainingWeightExhaustedAfter40WisconsinWomenRouteImport.update({
    id: '/blog/gaining-weight-exhausted-after-40-wisconsin-women',
    path: '/blog/gaining-weight-exhausted-after-40-wisconsin-women',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute =
  BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRouteImport.update({
    id: '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin',
    path: '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/clarity-session': typeof ClaritySessionRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/free-guide': typeof FreeGuideRoute
  '/michigan-discovery-call': typeof MichiganDiscoveryCallRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-treat': typeof WhatWeTreatRoute
  '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin': typeof BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute
  '/blog/gaining-weight-exhausted-after-40-wisconsin-women': typeof BlogGainingWeightExhaustedAfter40WisconsinWomenRoute
  '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin': typeof BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute
  '/blog/ozempic-not-working-michigan-wisconsin-women': typeof BlogOzempicNotWorkingMichiganWisconsinWomenRoute
  '/blog/perimenopause-in-your-30s-michigan-wisconsin': typeof BlogPerimenopauseInYour30sMichiganWisconsinRoute
  '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40': typeof BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route
  '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/clarity-session': typeof ClaritySessionRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/free-guide': typeof FreeGuideRoute
  '/michigan-discovery-call': typeof MichiganDiscoveryCallRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-treat': typeof WhatWeTreatRoute
  '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin': typeof BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute
  '/blog/gaining-weight-exhausted-after-40-wisconsin-women': typeof BlogGainingWeightExhaustedAfter40WisconsinWomenRoute
  '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin': typeof BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute
  '/blog/ozempic-not-working-michigan-wisconsin-women': typeof BlogOzempicNotWorkingMichiganWisconsinWomenRoute
  '/blog/perimenopause-in-your-30s-michigan-wisconsin': typeof BlogPerimenopauseInYour30sMichiganWisconsinRoute
  '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40': typeof BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route
  '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/clarity-session': typeof ClaritySessionRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/free-guide': typeof FreeGuideRoute
  '/michigan-discovery-call': typeof MichiganDiscoveryCallRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-treat': typeof WhatWeTreatRoute
  '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin': typeof BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute
  '/blog/gaining-weight-exhausted-after-40-wisconsin-women': typeof BlogGainingWeightExhaustedAfter40WisconsinWomenRoute
  '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin': typeof BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute
  '/blog/ozempic-not-working-michigan-wisconsin-women': typeof BlogOzempicNotWorkingMichiganWisconsinWomenRoute
  '/blog/perimenopause-in-your-30s-michigan-wisconsin': typeof BlogPerimenopauseInYour30sMichiganWisconsinRoute
  '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40': typeof BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route
  '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/clarity-session'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/free-guide'
    | '/michigan-discovery-call'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/what-we-treat'
    | '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin'
    | '/blog/gaining-weight-exhausted-after-40-wisconsin-women'
    | '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin'
    | '/blog/ozempic-not-working-michigan-wisconsin-women'
    | '/blog/perimenopause-in-your-30s-michigan-wisconsin'
    | '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40'
    | '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/clarity-session'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/free-guide'
    | '/michigan-discovery-call'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/what-we-treat'
    | '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin'
    | '/blog/gaining-weight-exhausted-after-40-wisconsin-women'
    | '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin'
    | '/blog/ozempic-not-working-michigan-wisconsin-women'
    | '/blog/perimenopause-in-your-30s-michigan-wisconsin'
    | '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40'
    | '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/clarity-session'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/free-guide'
    | '/michigan-discovery-call'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/what-we-treat'
    | '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin'
    | '/blog/gaining-weight-exhausted-after-40-wisconsin-women'
    | '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin'
    | '/blog/ozempic-not-working-michigan-wisconsin-women'
    | '/blog/perimenopause-in-your-30s-michigan-wisconsin'
    | '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40'
    | '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ClaritySessionRoute: typeof ClaritySessionRoute
  ContactRoute: typeof ContactRoute
  Free15MinCallWithKatieRoute: typeof Free15MinCallWithKatieRoute
  FreeGuideRoute: typeof FreeGuideRoute
  MichiganDiscoveryCallRoute: typeof MichiganDiscoveryCallRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WhatWeTreatRoute: typeof WhatWeTreatRoute
  BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute: typeof BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute
  BlogGainingWeightExhaustedAfter40WisconsinWomenRoute: typeof BlogGainingWeightExhaustedAfter40WisconsinWomenRoute
  BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute: typeof BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute
  BlogOzempicNotWorkingMichiganWisconsinWomenRoute: typeof BlogOzempicNotWorkingMichiganWisconsinWomenRoute
  BlogPerimenopauseInYour30sMichiganWisconsinRoute: typeof BlogPerimenopauseInYour30sMichiganWisconsinRoute
  BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route: typeof BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route
  BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute: typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-treat': {
      id: '/what-we-treat'
      path: '/what-we-treat'
      fullPath: '/what-we-treat'
      preLoaderRoute: typeof WhatWeTreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/michigan-discovery-call': {
      id: '/michigan-discovery-call'
      path: '/michigan-discovery-call'
      fullPath: '/michigan-discovery-call'
      preLoaderRoute: typeof MichiganDiscoveryCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-guide': {
      id: '/free-guide'
      path: '/free-guide'
      fullPath: '/free-guide'
      preLoaderRoute: typeof FreeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-15-min-call-with-katie': {
      id: '/free-15-min-call-with-katie'
      path: '/free-15-min-call-with-katie'
      fullPath: '/free-15-min-call-with-katie'
      preLoaderRoute: typeof Free15MinCallWithKatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarity-session': {
      id: '/clarity-session'
      path: '/clarity-session'
      fullPath: '/clarity-session'
      preLoaderRoute: typeof ClaritySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': {
      id: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
      path: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
      fullPath: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
      preLoaderRoute: typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40': {
      id: '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40'
      path: '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40'
      fullPath: '/blog/the-ultimate-guide-to-hormones-and-weight-resistance-over-40'
      preLoaderRoute: typeof BlogTheUltimateGuideToHormonesAndWeightResistanceOver40RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/perimenopause-in-your-30s-michigan-wisconsin': {
      id: '/blog/perimenopause-in-your-30s-michigan-wisconsin'
      path: '/blog/perimenopause-in-your-30s-michigan-wisconsin'
      fullPath: '/blog/perimenopause-in-your-30s-michigan-wisconsin'
      preLoaderRoute: typeof BlogPerimenopauseInYour30sMichiganWisconsinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ozempic-not-working-michigan-wisconsin-women': {
      id: '/blog/ozempic-not-working-michigan-wisconsin-women'
      path: '/blog/ozempic-not-working-michigan-wisconsin-women'
      fullPath: '/blog/ozempic-not-working-michigan-wisconsin-women'
      preLoaderRoute: typeof BlogOzempicNotWorkingMichiganWisconsinWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin': {
      id: '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin'
      path: '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin'
      fullPath: '/blog/hormonal-sleep-anxiety-women-michigan-wisconsin'
      preLoaderRoute: typeof BlogHormonalSleepAnxietyWomenMichiganWisconsinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/gaining-weight-exhausted-after-40-wisconsin-women': {
      id: '/blog/gaining-weight-exhausted-after-40-wisconsin-women'
      path: '/blog/gaining-weight-exhausted-after-40-wisconsin-women'
      fullPath: '/blog/gaining-weight-exhausted-after-40-wisconsin-women'
      preLoaderRoute: typeof BlogGainingWeightExhaustedAfter40WisconsinWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin': {
      id: '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin'
      path: '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin'
      fullPath: '/blog/bioidentical-hormone-therapy-guide-michigan-wisconsin'
      preLoaderRoute: typeof BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ClaritySessionRoute: ClaritySessionRoute,
  ContactRoute: ContactRoute,
  Free15MinCallWithKatieRoute: Free15MinCallWithKatieRoute,
  FreeGuideRoute: FreeGuideRoute,
  MichiganDiscoveryCallRoute: MichiganDiscoveryCallRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WhatWeTreatRoute: WhatWeTreatRoute,
  BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute:
    BlogBioidenticalHormoneTherapyGuideMichiganWisconsinRoute,
  BlogGainingWeightExhaustedAfter40WisconsinWomenRoute:
    BlogGainingWeightExhaustedAfter40WisconsinWomenRoute,
  BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute:
    BlogHormonalSleepAnxietyWomenMichiganWisconsinRoute,
  BlogOzempicNotWorkingMichiganWisconsinWomenRoute:
    BlogOzempicNotWorkingMichiganWisconsinWomenRoute,
  BlogPerimenopauseInYour30sMichiganWisconsinRoute:
    BlogPerimenopauseInYour30sMichiganWisconsinRoute,
  BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route:
    BlogTheUltimateGuideToHormonesAndWeightResistanceOver40Route,
  BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute:
    BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
